### ISSUE TITLE
Cancelled train is shown as normal

### ISSUE THREAD

**Issue by vukisoft** [stevenblair/commuter-bliss-uk#1]
My usual train is very often cancelled. I'd use this app to see early whether it is or not, to catch an earlier train. However it shows cancelled trains as normal as long as it's not the next (which is too late).
So it should be either shown with crossed font or not shown at all. (colour does not help for users of original pebble :))

**Comment by stevenblair** [comment]
Good point - I've changed the text to display "canc." instead of the ETA in minutes (which isn't that useful for a cancelled train) in version 1.86. There's no built-in support for strike-through fonts. I've only done some limited testing so far, so please feel free to report problems (or any other issues) here. Thanks!

**Comment by vukisoft** [comment]
Showing "canc" in ETA is good enough :) Thanks for the quick fix!

**Comment by vukisoft** [comment]
It would be very good if the NEXT train is cancelled, it should also show "canc." instead of the minutes left - got fooled many times I just looked at how much later the next departing and realized later that it was actually cancelled. It does not make sense anyway to show how much time left for the next train to NOT depart :)
It would really help the usability.

Thanks!

**Comment by stevenblair** [comment]
That is the expected behaviour. There could of course be a bug, or it could be that the information about the later cancellation isn't yet available in the data source. I'll try to test this to confirm.

**Comment by stevenblair** [comment]
I tested this using the PAD to GFD service, which is still disrupted following the recent derailment. This is the result:
![pebble-cancelled](https://cloud.githubusercontent.com/assets/785994/16231377/dd88015c-37bd-11e6-899b-3c872eee0a5a.png)

This doesn't completely rule out a bug, but it appears to work for the moment.

**Comment by vukisoft** [comment]
Well, bug or feature, border is so thin :) see https://devhumor.com/content/uploads//images/July2015/bug-vs-feature.jpg

Anyway, I'm proposing you show "canc." if the next train is cancelled, there's no point showing minutes there as the train will not depart at that time. It might seem redundant, but I think it helps a lot, for example I most often just look at the minutes only... (and I don't have colours on my watch :))

**Comment by stevenblair** [comment]
I see your point, and it might be worth adding this as an option.

I thought about completely hiding cancelled trains, and only showing running services (if there are any). But I decided it would be better to leave a placeholder so that it was clear which scheduled service was cancelled - it might be confusing if your regular expected services were mysteriously missing. (It also serves as an indication that it might be worth checking the website/app anyway, in case there's an underlying problem.)
